In [9]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix

import sys
import os.path as osp
import time
sys.path.append(osp.dirname(osp.dirname(osp.abspath('__file__'))))

import acoc
import utils
from utils import data_manager
from config import CLASSIFIER_CONFIG

In [18]:
# import some data to play with
iris = data_manager.load_data_set('digits')
X = iris.data
y = iris.target

# Split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

class_indices = list(set(y))

In [19]:
CLASSIFIER_CONFIG.max_level = 2
CLASSIFIER_CONFIG.level_convergence_rate = 5

clf = acoc.PolyACO(X.shape[1], class_indices, CLASSIFIER_CONFIG)
clf.train(X_train, y_train)
y_pred = clf.evaluate(X_test)
print("\rClassification score: {}".format(acoc.compute_score(y_pred, y_test)))

Classification score: 37.333333333333336


In [20]:
def plot_confusion_matrix(cm, title='Confusion matrix', cmap=plt.cm.Blues):
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(iris.target_names))
    plt.xticks(tick_marks, iris.target_names, rotation=45)
    plt.yticks(tick_marks, iris.target_names)
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')


# Compute confusion matrix
cm = confusion_matrix(y_test, y_pred)
np.set_printoptions(precision=2)
print('Confusion matrix, without normalization')
print(cm)
plt.figure()
plot_confusion_matrix(cm)

# Normalize the confusion matrix by row (i.e by the number of samples
# in each class)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)
plt.figure()
plot_confusion_matrix(cm_normalized, title='Normalized confusion matrix')

plt.show()

Confusion matrix, without normalization
[[ 8  0  4  4 19  1  0  1  0  0]
 [ 0 14  0  9 14  0  5  1  0  0]
 [ 0  4 14  4 16  0  5  1  0  0]
 [ 0  2  0 34  6  0  0  3  0  0]
 [ 0  1  0  2 32  0  0  3  0  0]
 [ 0  0  0 12 21  1 10  2  2  0]
 [ 0  0  1 13  9  0 29  0  0  0]
 [ 0  1  0  2 11  0  0 34  0  0]
 [ 0  1  3 10 33  0  0  1  0  0]
 [ 0  0  0 15 27  0  3  0  0  2]]
Normalized confusion matrix
[[ 0.22  0.    0.11  0.11  0.51  0.03  0.    0.03  0.    0.  ]
 [ 0.    0.33  0.    0.21  0.33  0.    0.12  0.02  0.    0.  ]
 [ 0.    0.09  0.32  0.09  0.36  0.    0.11  0.02  0.    0.  ]
 [ 0.    0.04  0.    0.76  0.13  0.    0.    0.07  0.    0.  ]
 [ 0.    0.03  0.    0.05  0.84  0.    0.    0.08  0.    0.  ]
 [ 0.    0.    0.    0.25  0.44  0.02  0.21  0.04  0.04  0.  ]
 [ 0.    0.    0.02  0.25  0.17  0.    0.56  0.    0.    0.  ]
 [ 0.    0.02  0.    0.04  0.23  0.    0.    0.71  0.    0.  ]
 [ 0.    0.02  0.06  0.21  0.69  0.    0.    0.02  0.    0.  ]
 [ 0.    0.    0.    0.32  0.57  0